using System;
using System.Data.Common;
using Smart.Database;
using Smart.Model;
using System.Collections.Generic;
using TGSmartControls.Model;

namespace TGSmartControls.DAL
{
	public class ComentarioDAL : Smart.Model.DataAccessObject
	{
		#region Automaticaly generated by Smart.AutoModeling 2.0
		public ComentarioDAL(DbConn pDbHnd) : base (pDbHnd) { }

		public ComentarioInfo Get(Int32 pCdComentario)
		{
			DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdComentario", pCdComentario));
			String sql = "SELECT cd_comentario, ds_comentario, ds_nomeusuario FROM COMENTARIO WHERE cd_comentario = @cdComentario";
			DbDataReader dr = DbHnd.ExecuteReader(sql);
			try
			{
				if (dr.Read())
				{
					ComentarioInfo info = new ComentarioInfo();
					if(dr["cd_comentario"] != System.DBNull.Value)
						info.CdComentario.Value = Convert.ToInt32(dr["cd_comentario"]);
					else
					{
						if (info.CdComentario.AllowsNull)
							info.CdComentario.IsNullValue = true;
					}
					if(dr["ds_comentario"] != System.DBNull.Value)
						info.DsComentario.Value = dr["ds_comentario"].ToString();
					else
					{
						if (info.DsComentario.AllowsNull)
							info.DsComentario.IsNullValue = true;
					}
					if(dr["ds_nomeusuario"] != System.DBNull.Value)
						info.DsNomeusuario.Value = dr["ds_nomeusuario"].ToString();
					else
					{
						if (info.DsNomeusuario.AllowsNull)
							info.DsNomeusuario.IsNullValue = true;
					}

					return info;
				}
				else
				{
					return null;
				}
			}
			finally
			{
				dr.Dispose();
			}
		}

		public Int32 Inserir(ComentarioInfo pInfo)
		{
			String insertCols = String.Empty;
			String insertValues = String.Empty;
			if (pInfo.DsComentario.ValueIsSet)
			{
				if (!pInfo.DsComentario.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsComentario", pInfo.DsComentario.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsComentario", System.DBNull.Value));
				}
				insertCols += ", " + pInfo.DsComentario.Name;
				insertValues += ", @dsComentario";
			}
			if (pInfo.DsNomeusuario.ValueIsSet)
			{
				if (!pInfo.DsNomeusuario.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsNomeusuario", pInfo.DsNomeusuario.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsNomeusuario", System.DBNull.Value));
				}
				insertCols += ", " + pInfo.DsNomeusuario.Name;
				insertValues += ", @dsNomeusuario";
			}
			insertCols = insertCols.Substring(2, insertCols.Length - 2);
			insertValues = insertValues.Substring(2, insertValues.Length - 2);
			return DbHnd.InsertGetInt32Key("INSERT INTO COMENTARIO (" + insertCols + ") VALUES (" + insertValues + ")", "cd_comentario");
		}

		public void Atualizar(Int32 pCdComentario, ComentarioInfo pInfo)
		{
			String upVars = String.Empty;
			if (pInfo.DsComentario.ValueIsSet)
			{
				if (!pInfo.DsComentario.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsComentario", pInfo.DsComentario.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsComentario", System.DBNull.Value));
				}
				upVars += ", " + pInfo.DsComentario.Name + " = @dsComentario";
			}
			if (pInfo.DsNomeusuario.ValueIsSet)
			{
				if (!pInfo.DsNomeusuario.IsNullValue)
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsNomeusuario", pInfo.DsNomeusuario.Value));
				}
				else
				{
					DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsNomeusuario", System.DBNull.Value));
				}
				upVars += ", " + pInfo.DsNomeusuario.Name + " = @dsNomeusuario";
			}
			upVars = upVars.Substring(2, upVars.Length - 2);

			String sqlWhere = String.Empty;
			DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdComentario", pCdComentario));
			sqlWhere += "cd_comentario = @cdComentario";
			sqlWhere = " WHERE " + sqlWhere;

			DbHnd.ExecuteNonQuery("UPDATE COMENTARIO SET " + upVars + sqlWhere);
		}

		public void Deletar(Int32 pCdComentario)
		{
			DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdComentario", pCdComentario));
			DbHnd.ExecuteNonQuery("DELETE FROM COMENTARIO WHERE cd_comentario = @cdComentario");
		}

		public List<ComentarioInfo> Listar()
		{
			List<ComentarioInfo> lstReturn = new List<ComentarioInfo>();

			String sqlSelect = "cd_comentario, ds_comentario, ds_nomeusuario";
			String sqlFrom = "COMENTARIO";
			String sqlWhere = BuildFilters();
			String sqlOrderBy = BuildOrderBy();
			String sql = "SELECT " + sqlSelect + " FROM " + sqlFrom + sqlWhere + sqlOrderBy;
			using (DbDataReader dr = DbHnd.ExecuteReader(sql))
			{
				while (dr.Read())
				{
					ComentarioInfo info = new ComentarioInfo();
					if(dr["cd_comentario"] != System.DBNull.Value)
						info.CdComentario.Value = Convert.ToInt32(dr["cd_comentario"]);
					else
					{
						if (info.CdComentario.AllowsNull)
							info.CdComentario.IsNullValue = true;
					}
					if(dr["ds_comentario"] != System.DBNull.Value)
						info.DsComentario.Value = dr["ds_comentario"].ToString();
					else
					{
						if (info.DsComentario.AllowsNull)
							info.DsComentario.IsNullValue = true;
					}
					if(dr["ds_nomeusuario"] != System.DBNull.Value)
						info.DsNomeusuario.Value = dr["ds_nomeusuario"].ToString();
					else
					{
						if (info.DsNomeusuario.AllowsNull)
							info.DsNomeusuario.IsNullValue = true;
					}
					lstReturn.Add(info);
				}
			}
			return lstReturn;
		}

		public List<ComentarioInfo> ListarPaginado()
		{
			List<ComentarioInfo> lstReturn = new List<ComentarioInfo>();

			String sqlSelect = "cd_comentario, ds_comentario, ds_nomeusuario";
			String sqlFrom = "COMENTARIO";
			String sqlWhere = BuildPagedFilters();
			String sqlOrderBy = BuildPagedOrderBy();
			String sql = new Smart.Database.SQL.Translator(DbHnd.ProviderName).MontarSqlPaginado(sqlSelect, sqlFrom, sqlWhere, sqlOrderBy, this.Filters.PageNumber, this.Filters.EntriesPerPage);
			using (DbDataReader dr = DbHnd.ExecuteReader(sql))
			{
				while (dr.Read())
				{
					ComentarioInfo info = new ComentarioInfo();
					if(dr["cd_comentario"] != System.DBNull.Value)
						info.CdComentario.Value = Convert.ToInt32(dr["cd_comentario"]);
					else
					{
						if (info.CdComentario.AllowsNull)
							info.CdComentario.IsNullValue = true;
					}
					if(dr["ds_comentario"] != System.DBNull.Value)
						info.DsComentario.Value = dr["ds_comentario"].ToString();
					else
					{
						if (info.DsComentario.AllowsNull)
							info.DsComentario.IsNullValue = true;
					}
					if(dr["ds_nomeusuario"] != System.DBNull.Value)
						info.DsNomeusuario.Value = dr["ds_nomeusuario"].ToString();
					else
					{
						if (info.DsNomeusuario.AllowsNull)
							info.DsNomeusuario.IsNullValue = true;
					}
					lstReturn.Add(info);
				}
			}
			return lstReturn;
		}

		public Int32 GetTotalRegistros()
		{
			String sqlSelect = "COUNT(cd_comentario)";
			String sqlWhere = BuildFilters();
			object obj = DbHnd.ExecuteScalar("SELECT " + sqlSelect + " FROM COMENTARIO " + sqlWhere);
			return Convert.ToInt32(obj);
		}
		#endregion
	}
}
