using Exercicio.Model;
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Smart.Database;

namespace Exercicio.DAL
{
    public class ContatoDAL : Smart.Model.DataAccessObject
    {
        
        #region Automaticaly generated by Smart.AutoModeling 2.0
        public ContatoDAL(DbConn pDbHnd) : base(pDbHnd) { }

        public ContatoInfo Get(Int32 pCdContato)

        {
            DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdContato", pCdContato));
            String sql = "SELECT dt_nasci, cd_contato, cd_estado, ds_endereco, ds_nome, ds_email, ds_cpf, ds_sexo, ds_cidade FROM CONTATO WHERE cd_contato = @cdContato";
            DbDataReader dr = DbHnd.ExecuteReader(sql);
            try
            {
                if (dr.Read())
                {
                    ContatoInfo info = new ContatoInfo();
                    if (dr["dt_nasci"] != System.DBNull.Value)
                        info.DtNasci.Value = Convert.ToDateTime(dr["dt_nasci"]);
                    else
                    {
                        if (info.DtNasci.AllowsNull)
                            info.DtNasci.IsNullValue = true;
                    }
                    if (dr["cd_contato"] != System.DBNull.Value)
                        info.CdContato.Value = Convert.ToInt32(dr["cd_contato"]);
                    else
                    {
                        if (info.CdContato.AllowsNull)
                            info.CdContato.IsNullValue = true;
                    }
                    if (dr["cd_estado"] != System.DBNull.Value)
                        info.CdEstado.Value = Convert.ToInt32(dr["cd_estado"]);
                    else
                    {
                        if (info.CdEstado.AllowsNull)
                            info.CdEstado.IsNullValue = true;
                    }
                    if (dr["ds_endereco"] != System.DBNull.Value)
                        info.DsEndereco.Value = dr["ds_endereco"].ToString();
                    else
                    {
                        if (info.DsEndereco.AllowsNull)
                            info.DsEndereco.IsNullValue = true;
                    }
                    if (dr["ds_nome"] != System.DBNull.Value)
                        info.DsNome.Value = dr["ds_nome"].ToString();
                    else
                    {
                        if (info.DsNome.AllowsNull)
                            info.DsNome.IsNullValue = true;
                    }
                    if (dr["ds_email"] != System.DBNull.Value)
                        info.DsEmail.Value = dr["ds_email"].ToString();
                    else
                    {
                        if (info.DsEmail.AllowsNull)
                            info.DsEmail.IsNullValue = true;
                    }
                    if (dr["ds_cpf"] != System.DBNull.Value)
                        info.DsCpf.Value = dr["ds_cpf"].ToString();
                    else
                    {
                        if (info.DsCpf.AllowsNull)
                            info.DsCpf.IsNullValue = true;
                    }
                    if (dr["ds_sexo"] != System.DBNull.Value)
                        info.DsSexo.Value = dr["ds_sexo"].ToString();
                    else
                    {
                        if (info.DsSexo.AllowsNull)
                            info.DsSexo.IsNullValue = true;
                    }
                    if (dr["ds_cidade"] != System.DBNull.Value)
                        info.DsCidade.Value = dr["ds_cidade"].ToString();
                    else
                    {
                        if (info.DsCidade.AllowsNull)
                            info.DsCidade.IsNullValue = true;
                    }

                    return info;
                }
                else
                {
                    return null;
                }
            }
            finally
            {
                dr.Dispose();
            }
        }

        public Int32 Inserir(ContatoInfo pInfo)
        {
            String insertCols = String.Empty;
            String insertValues = String.Empty;
            if (pInfo.DtNasci.ValueIsSet)
            {
                if (!pInfo.DtNasci.IsNullValue)
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dtNasci", pInfo.DtNasci.Value));
                }
                else
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dtNasci", System.DBNull.Value));
                }
                insertCols += ", " + pInfo.DtNasci.Name;
                insertValues += ", @dtNasci";
            }
            if (pInfo.CdEstado.ValueIsSet)
            {
                if (!pInfo.CdEstado.IsNullValue)
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdEstado", pInfo.CdEstado.Value));
                }
                else
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdEstado", System.DBNull.Value));
                }
                insertCols += ", " + pInfo.CdEstado.Name;
                insertValues += ", @cdEstado";
            }
            if (pInfo.DsEndereco.ValueIsSet)
            {
                if (!pInfo.DsEndereco.IsNullValue)
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsEndereco", pInfo.DsEndereco.Value));
                }
                else
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsEndereco", System.DBNull.Value));
                }
                insertCols += ", " + pInfo.DsEndereco.Name;
                insertValues += ", @dsEndereco";
            }
            if (pInfo.DsNome.ValueIsSet)
            {
                if (!pInfo.DsNome.IsNullValue)
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsNome", pInfo.DsNome.Value));
                }
                else
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsNome", System.DBNull.Value));
                }
                insertCols += ", " + pInfo.DsNome.Name;
                insertValues += ", @dsNome";
            }
            if (pInfo.DsEmail.ValueIsSet)
            {
                if (!pInfo.DsEmail.IsNullValue)
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsEmail", pInfo.DsEmail.Value));
                }
                else
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsEmail", System.DBNull.Value));
                }
                insertCols += ", " + pInfo.DsEmail.Name;
                insertValues += ", @dsEmail";
            }
            if (pInfo.DsCpf.ValueIsSet)
            {
                if (!pInfo.DsCpf.IsNullValue)
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsCpf", pInfo.DsCpf.Value));
                }
                else
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsCpf", System.DBNull.Value));
                }
                insertCols += ", " + pInfo.DsCpf.Name;
                insertValues += ", @dsCpf";
            }
            if (pInfo.DsSexo.ValueIsSet)
            {
                if (!pInfo.DsSexo.IsNullValue)
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsSexo", pInfo.DsSexo.Value));
                }
                else
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsSexo", System.DBNull.Value));
                }
                insertCols += ", " + pInfo.DsSexo.Name;
                insertValues += ", @dsSexo";
            }
            if (pInfo.DsCidade.ValueIsSet)
            {
                if (!pInfo.DsCidade.IsNullValue)
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsCidade", pInfo.DsCidade.Value));
                }
                else
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsCidade", System.DBNull.Value));
                }
                insertCols += ", " + pInfo.DsCidade.Name;
                insertValues += ", @dsCidade";
            }
            insertCols = insertCols.Substring(2, insertCols.Length - 2);
            insertValues = insertValues.Substring(2, insertValues.Length - 2);
            return DbHnd.InsertGetInt32Key("INSERT INTO CONTATO (" + insertCols + ") VALUES (" + insertValues + ")", "cd_contato");
        }

        public void Atualizar(Int32 pCdContato, ContatoInfo pInfo)
        {
            String upVars = String.Empty;
            if (pInfo.DtNasci.ValueIsSet)
            {
                if (!pInfo.DtNasci.IsNullValue)
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dtNasci", pInfo.DtNasci.Value));
                }
                else
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dtNasci", System.DBNull.Value));
                }
                upVars += ", " + pInfo.DtNasci.Name + " = @dtNasci";
            }
            if (pInfo.CdEstado.ValueIsSet)
            {
                if (!pInfo.CdEstado.IsNullValue)
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdEstado", pInfo.CdEstado.Value));
                }
                else
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdEstado", System.DBNull.Value));
                }
                upVars += ", " + pInfo.CdEstado.Name + " = @cdEstado";
            }
            if (pInfo.DsEndereco.ValueIsSet)
            {
                if (!pInfo.DsEndereco.IsNullValue)
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsEndereco", pInfo.DsEndereco.Value));
                }
                else
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsEndereco", System.DBNull.Value));
                }
                upVars += ", " + pInfo.DsEndereco.Name + " = @dsEndereco";
            }
            if (pInfo.DsNome.ValueIsSet)
            {
                if (!pInfo.DsNome.IsNullValue)
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsNome", pInfo.DsNome.Value));
                }
                else
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsNome", System.DBNull.Value));
                }
                upVars += ", " + pInfo.DsNome.Name + " = @dsNome";
            }
            if (pInfo.DsEmail.ValueIsSet)
            {
                if (!pInfo.DsEmail.IsNullValue)
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsEmail", pInfo.DsEmail.Value));
                }
                else
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsEmail", System.DBNull.Value));
                }
                upVars += ", " + pInfo.DsEmail.Name + " = @dsEmail";
            }
            if (pInfo.DsCpf.ValueIsSet)
            {
                if (!pInfo.DsCpf.IsNullValue)
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsCpf", pInfo.DsCpf.Value));
                }
                else
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsCpf", System.DBNull.Value));
                }
                upVars += ", " + pInfo.DsCpf.Name + " = @dsCpf";
            }
            if (pInfo.DsSexo.ValueIsSet)
            {
                if (!pInfo.DsSexo.IsNullValue)
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsSexo", pInfo.DsSexo.Value));
                }
                else
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsSexo", System.DBNull.Value));
                }
                upVars += ", " + pInfo.DsSexo.Name + " = @dsSexo";
            }
            if (pInfo.DsCidade.ValueIsSet)
            {
                if (!pInfo.DsCidade.IsNullValue)
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsCidade", pInfo.DsCidade.Value));
                }
                else
                {
                    DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@dsCidade", System.DBNull.Value));
                }
                upVars += ", " + pInfo.DsCidade.Name + " = @dsCidade";
            }
            upVars = upVars.Substring(2, upVars.Length - 2);

            String sqlWhere = String.Empty;
            DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdContato", pCdContato));
            sqlWhere += "cd_contato = @cdContato";
            sqlWhere = " WHERE " + sqlWhere;

            DbHnd.ExecuteNonQuery("UPDATE CONTATO SET " + upVars + sqlWhere);
        }

        public void Deletar(Int32 pCdContato)
        {
            DbHnd.Parametros.Add(new System.Data.SqlClient.SqlParameter("@cdContato", pCdContato));
            DbHnd.ExecuteNonQuery("DELETE FROM CONTATO WHERE cd_contato = @cdContato");
        }

        public List<ContatoInfo> Listar()
        {
            List<ContatoInfo> lstReturn = new List<ContatoInfo>();

            String sqlSelect = "dt_nasci, cd_contato, cd_estado, ds_endereco, ds_nome, ds_email, ds_cpf, ds_sexo, ds_cidade";
            String sqlFrom = "CONTATO";
            String sqlWhere = BuildFilters();
            String sqlOrderBy = BuildOrderBy();
            String sql = "SELECT " + sqlSelect + " FROM " + sqlFrom + sqlWhere + sqlOrderBy;
            using (DbDataReader dr = DbHnd.ExecuteReader(sql))
            {
                while (dr.Read())
                {
                    ContatoInfo info = new ContatoInfo();
                    if (dr["dt_nasci"] != System.DBNull.Value)
                        info.DtNasci.Value = Convert.ToDateTime(dr["dt_nasci"]);
                    else
                    {
                        if (info.DtNasci.AllowsNull)
                            info.DtNasci.IsNullValue = true;
                    }
                    if (dr["cd_contato"] != System.DBNull.Value)
                        info.CdContato.Value = Convert.ToInt32(dr["cd_contato"]);
                    else
                    {
                        if (info.CdContato.AllowsNull)
                            info.CdContato.IsNullValue = true;
                    }
                    if (dr["cd_estado"] != System.DBNull.Value)
                        info.CdEstado.Value = Convert.ToInt32(dr["cd_estado"]);
                    else
                    {
                        if (info.CdEstado.AllowsNull)
                            info.CdEstado.IsNullValue = true;
                    }
                    if (dr["ds_endereco"] != System.DBNull.Value)
                        info.DsEndereco.Value = dr["ds_endereco"].ToString();
                    else
                    {
                        if (info.DsEndereco.AllowsNull)
                            info.DsEndereco.IsNullValue = true;
                    }
                    if (dr["ds_nome"] != System.DBNull.Value)
                        info.DsNome.Value = dr["ds_nome"].ToString();
                    else
                    {
                        if (info.DsNome.AllowsNull)
                            info.DsNome.IsNullValue = true;
                    }
                    if (dr["ds_email"] != System.DBNull.Value)
                        info.DsEmail.Value = dr["ds_email"].ToString();
                    else
                    {
                        if (info.DsEmail.AllowsNull)
                            info.DsEmail.IsNullValue = true;
                    }
                    if (dr["ds_cpf"] != System.DBNull.Value)
                        info.DsCpf.Value = dr["ds_cpf"].ToString();
                    else
                    {
                        if (info.DsCpf.AllowsNull)
                            info.DsCpf.IsNullValue = true;
                    }
                    if (dr["ds_sexo"] != System.DBNull.Value)
                        info.DsSexo.Value = dr["ds_sexo"].ToString();
                    else
                    {
                        if (info.DsSexo.AllowsNull)
                            info.DsSexo.IsNullValue = true;
                    }
                    if (dr["ds_cidade"] != System.DBNull.Value)
                        info.DsCidade.Value = dr["ds_cidade"].ToString();
                    else
                    {
                        if (info.DsCidade.AllowsNull)
                            info.DsCidade.IsNullValue = true;
                    }
                    lstReturn.Add(info);
                }
            }
            return lstReturn;
        }

        public List<ContatoInfo> ListarPaginado()
        {
            List<ContatoInfo> lstReturn = new List<ContatoInfo>();

            String sqlSelect = "dt_nasci, cd_contato, cd_estado, ds_endereco, ds_nome, ds_email, ds_cpf, ds_sexo, ds_cidade";
            String sqlFrom = "CONTATO";
            String sqlWhere = BuildPagedFilters();
            String sqlOrderBy = BuildPagedOrderBy();
            String sql = new Smart.Database.SQL.Translator(DbHnd.ProviderName).MontarSqlPaginado(sqlSelect, sqlFrom, sqlWhere, sqlOrderBy, this.Filters.PageNumber, this.Filters.EntriesPerPage);
            using (DbDataReader dr = DbHnd.ExecuteReader(sql))
            {
                while (dr.Read())
                {
                    ContatoInfo info = new ContatoInfo();
                    if (dr["dt_nasci"] != System.DBNull.Value)
                        info.DtNasci.Value = Convert.ToDateTime(dr["dt_nasci"]);
                    else
                    {
                        if (info.DtNasci.AllowsNull)
                            info.DtNasci.IsNullValue = true;
                    }
                    if (dr["cd_contato"] != System.DBNull.Value)
                        info.CdContato.Value = Convert.ToInt32(dr["cd_contato"]);
                    else
                    {
                        if (info.CdContato.AllowsNull)
                            info.CdContato.IsNullValue = true;
                    }
                    if (dr["cd_estado"] != System.DBNull.Value)
                        info.CdEstado.Value = Convert.ToInt32(dr["cd_estado"]);
                    else
                    {
                        if (info.CdEstado.AllowsNull)
                            info.CdEstado.IsNullValue = true;
                    }
                    if (dr["ds_endereco"] != System.DBNull.Value)
                        info.DsEndereco.Value = dr["ds_endereco"].ToString();
                    else
                    {
                        if (info.DsEndereco.AllowsNull)
                            info.DsEndereco.IsNullValue = true;
                    }
                    if (dr["ds_nome"] != System.DBNull.Value)
                        info.DsNome.Value = dr["ds_nome"].ToString();
                    else
                    {
                        if (info.DsNome.AllowsNull)
                            info.DsNome.IsNullValue = true;
                    }
                    if (dr["ds_email"] != System.DBNull.Value)
                        info.DsEmail.Value = dr["ds_email"].ToString();
                    else
                    {
                        if (info.DsEmail.AllowsNull)
                            info.DsEmail.IsNullValue = true;
                    }
                    if (dr["ds_cpf"] != System.DBNull.Value)
                        info.DsCpf.Value = dr["ds_cpf"].ToString();
                    else
                    {
                        if (info.DsCpf.AllowsNull)
                            info.DsCpf.IsNullValue = true;
                    }
                    if (dr["ds_sexo"] != System.DBNull.Value)
                        info.DsSexo.Value = dr["ds_sexo"].ToString();
                    else
                    {
                        if (info.DsSexo.AllowsNull)
                            info.DsSexo.IsNullValue = true;
                    }
                    if (dr["ds_cidade"] != System.DBNull.Value)
                        info.DsCidade.Value = dr["ds_cidade"].ToString();
                    else
                    {
                        if (info.DsCidade.AllowsNull)
                            info.DsCidade.IsNullValue = true;
                    }
                    lstReturn.Add(info);
                }
            }
            return lstReturn;
        }
        #endregion
    }
}
