using System;
using Smart.Model;

namespace TGSmartControls.Model
{
	public class CidadeInfo : Smart.Model.DbTable
	{
		#region Automaticaly generated by Smart.AutoModeling 2.0
		public CidadeInfo()
		{
		}

		/// <summary>
		/// All fields constructor (Except Auto Increment)
		/// </summary>
		/// <param name="pCdEstado">Default value for property 'CdEstado'</param>
		/// <param name="pDsNome">Default value for property 'DsNome'</param>
		public CidadeInfo(Int32 pCdEstado, String pDsNome)
		{
			_CdEstado.Value = pCdEstado;
			_DsNome.Value = pDsNome;
		}

		static public Int32DbField GetCdCidade()
		{
			return _GetCdCidade();
		}
		static public Int32DbField GetCdCidade(Int32 pCdCidade)
		{
			Int32DbField dbfield = _GetCdCidade();
			dbfield.Value = pCdCidade;
			return dbfield;
		}
		static Int32DbField _GetCdCidade()
		{
			Int32DbField dbfield = new Int32DbField();
			dbfield.AllowsNull = false;
			dbfield.DataTypeName = "int";
			dbfield.DefaultValue = "";
			dbfield.IsAutoId = true;
			dbfield.IsPrimaryKey = true;
			dbfield.Name = "cd_cidade";
			dbfield.Scale = 0;
			dbfield.Size = 4;
			dbfield.TableName = "CIDADE";
			return dbfield;
		}
		static public Int32DbField GetCdEstado()
		{
			return _GetCdEstado();
		}
		static public Int32DbField GetCdEstado(Int32 pCdEstado)
		{
			Int32DbField dbfield = _GetCdEstado();
			dbfield.Value = pCdEstado;
			return dbfield;
		}
		static Int32DbField _GetCdEstado()
		{
			Int32DbField dbfield = new Int32DbField();
			dbfield.AllowsNull = false;
			dbfield.DataTypeName = "int";
			dbfield.DefaultValue = "";
			dbfield.IsAutoId = false;
			dbfield.IsPrimaryKey = false;
			dbfield.Name = "cd_estado";
			dbfield.Scale = 0;
			dbfield.Size = 4;
			dbfield.TableName = "CIDADE";
			return dbfield;
		}
		static public StringDbField GetDsNome()
		{
			return _GetDsNome();
		}
		static public StringDbField GetDsNome(String pDsNome)
		{
			StringDbField dbfield = _GetDsNome();
			dbfield.Value = pDsNome;
			return dbfield;
		}
		static StringDbField _GetDsNome()
		{
			StringDbField dbfield = new StringDbField();
			dbfield.AllowsNull = false;
			dbfield.DataTypeName = "nvarchar";
			dbfield.DefaultValue = "";
			dbfield.IsAutoId = false;
			dbfield.IsPrimaryKey = false;
			dbfield.Name = "ds_nome";
			dbfield.Scale = 0;
			dbfield.Size = 255;
			dbfield.TableName = "CIDADE";
			return dbfield;
		}
		private Int32DbField _CdCidade = GetCdCidade();
		public Int32DbField CdCidade
		{
			get { return _CdCidade; }
			set { _CdCidade = value; }
		}

		private Int32DbField _CdEstado = GetCdEstado();
		public Int32DbField CdEstado
		{
			get { return _CdEstado; }
			set { _CdEstado = value; }
		}

		private StringDbField _DsNome = GetDsNome();
		public StringDbField DsNome
		{
			get { return _DsNome; }
			set { _DsNome = value; }
		}

		#endregion
	}
}
