using System;
using Smart.Model;

namespace TGSmartControls.Model
{
	public class ComentarioInfo : Smart.Model.DbTable
	{
		#region Automaticaly generated by Smart.AutoModeling 2.0
		public ComentarioInfo()
		{
		}

		/// <summary>
		/// All fields constructor (Except Auto Increment)
		/// </summary>
		/// <param name="pDsComentario">Default value for property 'DsComentario'</param>
		/// <param name="pDsNomeusuario">Default value for property 'DsNomeusuario'</param>
		public ComentarioInfo(String pDsComentario, String pDsNomeusuario)
		{
			_DsComentario.Value = pDsComentario;
			_DsNomeusuario.Value = pDsNomeusuario;
		}

		static public Int32DbField GetCdComentario()
		{
			return _GetCdComentario();
		}
		static public Int32DbField GetCdComentario(Int32 pCdComentario)
		{
			Int32DbField dbfield = _GetCdComentario();
			dbfield.Value = pCdComentario;
			return dbfield;
		}
		static Int32DbField _GetCdComentario()
		{
			Int32DbField dbfield = new Int32DbField();
			dbfield.AllowsNull = false;
			dbfield.DataTypeName = "int";
			dbfield.DefaultValue = "";
			dbfield.IsAutoId = true;
			dbfield.IsPrimaryKey = true;
			dbfield.Name = "cd_comentario";
			dbfield.Scale = 0;
			dbfield.Size = 4;
			dbfield.TableName = "COMENTARIO";
			return dbfield;
		}
		static public StringDbField GetDsComentario()
		{
			return _GetDsComentario();
		}
		static public StringDbField GetDsComentario(String pDsComentario)
		{
			StringDbField dbfield = _GetDsComentario();
			dbfield.Value = pDsComentario;
			return dbfield;
		}
		static StringDbField _GetDsComentario()
		{
			StringDbField dbfield = new StringDbField();
			dbfield.AllowsNull = false;
			dbfield.DataTypeName = "nvarchar";
			dbfield.DefaultValue = "";
			dbfield.IsAutoId = false;
			dbfield.IsPrimaryKey = false;
			dbfield.Name = "ds_comentario";
			dbfield.Scale = 0;
			dbfield.Size = 255;
			dbfield.TableName = "COMENTARIO";
			return dbfield;
		}
		static public StringDbField GetDsNomeusuario()
		{
			return _GetDsNomeusuario();
		}
		static public StringDbField GetDsNomeusuario(String pDsNomeusuario)
		{
			StringDbField dbfield = _GetDsNomeusuario();
			dbfield.Value = pDsNomeusuario;
			return dbfield;
		}
		static StringDbField _GetDsNomeusuario()
		{
			StringDbField dbfield = new StringDbField();
			dbfield.AllowsNull = false;
			dbfield.DataTypeName = "nvarchar";
			dbfield.DefaultValue = "";
			dbfield.IsAutoId = false;
			dbfield.IsPrimaryKey = false;
			dbfield.Name = "ds_nomeusuario";
			dbfield.Scale = 0;
			dbfield.Size = 50;
			dbfield.TableName = "COMENTARIO";
			return dbfield;
		}
		private Int32DbField _CdComentario = GetCdComentario();
		public Int32DbField CdComentario
		{
			get { return _CdComentario; }
			set { _CdComentario = value; }
		}

		private StringDbField _DsComentario = GetDsComentario();
		public StringDbField DsComentario
		{
			get { return _DsComentario; }
			set { _DsComentario = value; }
		}

		private StringDbField _DsNomeusuario = GetDsNomeusuario();
		public StringDbField DsNomeusuario
		{
			get { return _DsNomeusuario; }
			set { _DsNomeusuario = value; }
		}

		#endregion
	}
}
