using System;
using Smart.Model;

namespace TGSmartControls.Model
{
	public class UsuarioInfo : Smart.Model.DbTable
	{
		#region Automaticaly generated by Smart.AutoModeling 2.0
		public UsuarioInfo()
		{
		}

		/// <summary>
		/// All fields constructor (Except Auto Increment)
		/// </summary>
		/// <param name="pDtNasc">Default value for property 'DtNasc'</param>
		/// <param name="pStAtivo">Default value for property 'StAtivo'</param>
		/// <param name="pCdCidadenasc">Default value for property 'CdCidadenasc'</param>
		/// <param name="pDsNome">Default value for property 'DsNome'</param>
		/// <param name="pDsEmail">Default value for property 'DsEmail'</param>
		public UsuarioInfo(DateTime pDtNasc, Byte pStAtivo, Int32 pCdCidadenasc, String pDsNome, String pDsEmail)
		{
			_DtNasc.Value = pDtNasc;
			_StAtivo.Value = pStAtivo;
			_CdCidadenasc.Value = pCdCidadenasc;
			_DsNome.Value = pDsNome;
			_DsEmail.Value = pDsEmail;
		}

		static public DateTimeDbField GetDtNasc()
		{
			return _GetDtNasc();
		}
		static public DateTimeDbField GetDtNasc(DateTime pDtNasc)
		{
			DateTimeDbField dbfield = _GetDtNasc();
			dbfield.Value = pDtNasc;
			return dbfield;
		}
		static DateTimeDbField _GetDtNasc()
		{
			DateTimeDbField dbfield = new DateTimeDbField();
			dbfield.AllowsNull = false;
			dbfield.DataTypeName = "date";
			dbfield.DefaultValue = "";
			dbfield.IsAutoId = false;
			dbfield.IsPrimaryKey = false;
			dbfield.Name = "dt_nasc";
			dbfield.Scale = 0;
			dbfield.Size = 3;
			dbfield.TableName = "USUARIO";
			return dbfield;
		}
		static public ByteDbField GetStAtivo()
		{
			return _GetStAtivo();
		}
		static public ByteDbField GetStAtivo(Byte pStAtivo)
		{
			ByteDbField dbfield = _GetStAtivo();
			dbfield.Value = pStAtivo;
			return dbfield;
		}
		static ByteDbField _GetStAtivo()
		{
			ByteDbField dbfield = new ByteDbField();
			dbfield.AllowsNull = false;
			dbfield.DataTypeName = "tinyint";
			dbfield.DefaultValue = "";
			dbfield.IsAutoId = false;
			dbfield.IsPrimaryKey = false;
			dbfield.Name = "st_ativo";
			dbfield.Scale = 0;
			dbfield.Size = 1;
			dbfield.TableName = "USUARIO";
			return dbfield;
		}
		static public Int32DbField GetCdCidadenasc()
		{
			return _GetCdCidadenasc();
		}
		static public Int32DbField GetCdCidadenasc(Int32 pCdCidadenasc)
		{
			Int32DbField dbfield = _GetCdCidadenasc();
			dbfield.Value = pCdCidadenasc;
			return dbfield;
		}
		static Int32DbField _GetCdCidadenasc()
		{
			Int32DbField dbfield = new Int32DbField();
			dbfield.AllowsNull = false;
			dbfield.DataTypeName = "int";
			dbfield.DefaultValue = "";
			dbfield.IsAutoId = false;
			dbfield.IsPrimaryKey = false;
			dbfield.Name = "cd_cidadenasc";
			dbfield.Scale = 0;
			dbfield.Size = 4;
			dbfield.TableName = "USUARIO";
			return dbfield;
		}
		static public Int32DbField GetCdUsuario()
		{
			return _GetCdUsuario();
		}
		static public Int32DbField GetCdUsuario(Int32 pCdUsuario)
		{
			Int32DbField dbfield = _GetCdUsuario();
			dbfield.Value = pCdUsuario;
			return dbfield;
		}
		static Int32DbField _GetCdUsuario()
		{
			Int32DbField dbfield = new Int32DbField();
			dbfield.AllowsNull = false;
			dbfield.DataTypeName = "int";
			dbfield.DefaultValue = "";
			dbfield.IsAutoId = true;
			dbfield.IsPrimaryKey = true;
			dbfield.Name = "cd_usuario";
			dbfield.Scale = 0;
			dbfield.Size = 4;
			dbfield.TableName = "USUARIO";
			return dbfield;
		}
		static public StringDbField GetDsNome()
		{
			return _GetDsNome();
		}
		static public StringDbField GetDsNome(String pDsNome)
		{
			StringDbField dbfield = _GetDsNome();
			dbfield.Value = pDsNome;
			return dbfield;
		}
		static StringDbField _GetDsNome()
		{
			StringDbField dbfield = new StringDbField();
			dbfield.AllowsNull = false;
			dbfield.DataTypeName = "nvarchar";
			dbfield.DefaultValue = "";
			dbfield.IsAutoId = false;
			dbfield.IsPrimaryKey = false;
			dbfield.Name = "ds_nome";
			dbfield.Scale = 0;
			dbfield.Size = 255;
			dbfield.TableName = "USUARIO";
			return dbfield;
		}
		static public StringDbField GetDsEmail()
		{
			return _GetDsEmail();
		}
		static public StringDbField GetDsEmail(String pDsEmail)
		{
			StringDbField dbfield = _GetDsEmail();
			dbfield.Value = pDsEmail;
			return dbfield;
		}
		static StringDbField _GetDsEmail()
		{
			StringDbField dbfield = new StringDbField();
			dbfield.AllowsNull = false;
			dbfield.DataTypeName = "nvarchar";
			dbfield.DefaultValue = "";
			dbfield.IsAutoId = false;
			dbfield.IsPrimaryKey = false;
			dbfield.Name = "ds_email";
			dbfield.Scale = 0;
			dbfield.Size = 255;
			dbfield.TableName = "USUARIO";
			return dbfield;
		}
		private DateTimeDbField _DtNasc = GetDtNasc();
		public DateTimeDbField DtNasc
		{
			get { return _DtNasc; }
			set { _DtNasc = value; }
		}

		private ByteDbField _StAtivo = GetStAtivo();
		public ByteDbField StAtivo
		{
			get { return _StAtivo; }
			set { _StAtivo = value; }
		}

		private Int32DbField _CdCidadenasc = GetCdCidadenasc();
		public Int32DbField CdCidadenasc
		{
			get { return _CdCidadenasc; }
			set { _CdCidadenasc = value; }
		}

		private Int32DbField _CdUsuario = GetCdUsuario();
		public Int32DbField CdUsuario
		{
			get { return _CdUsuario; }
			set { _CdUsuario = value; }
		}

		private StringDbField _DsNome = GetDsNome();
		public StringDbField DsNome
		{
			get { return _DsNome; }
			set { _DsNome = value; }
		}

		private StringDbField _DsEmail = GetDsEmail();
		public StringDbField DsEmail
		{
			get { return _DsEmail; }
			set { _DsEmail = value; }
		}

		#endregion
	}
}
